### ISSUE TITLE
Failure message: Not authenticated

### ISSUE THREAD

**Issue by march5350** [vincentbitter/koreader-calibre-web-sync#8]
Hiya,

I created the following stack in Docker that includes both Calibre-web as well as KOReader-Calibre-Web-Sync. 

```
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - "/config:/config"
      - "/books:/cwa-book-ingest"
      - "/mnt/books/ebooks:/calibre-library"
    ports:
      - "8083:8083"
    restart: unless-stopped
    networks:
      - "calibre"
  koreader-calibre-web-sync:
    image: vincentbitter/koreader-calibre-web-sync:latest
    container_name: koreader-calibre-web-sync
    ports: 
      - "5000:5000"
    restart: unless-stopped
    networks:
      - "calibre"
networks:
  calibre:
    name: calibre
    driver: bridge
```

Calibre works just fine, but when I login on Progress sync within KOReader I get the following error: "Unknown server error". When I check the logs of my KCWS container, it show me the following message:
```
info: Sync.Configuration.CustomAuthenticationHandler[7]
      custom was not authenticated. Failure message: Not authenticated
```

Did I miss something setting KCWS up, or could this be a bug?
